/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Confirms the process is running. Touches nothing external, so it keeps passing even when the database is down.
         */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Confirms the service can reach its database and serve traffic. Returns 503 when the database is unreachable.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Own profile and stats
         * @description Returns the signed-in user's local profile. On a user's first authenticated request, the local profile is created first (D-12).
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update own profile
         * @description Updates the signed-in user's locally owned fields: username, bio, and technology stack. Returns the updated profile, the same shape as GET /users/me. Subject to the write rate limit.
         */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public profile
         * @description Any user's public profile. No authentication needed. The username is matched case-insensitively.
         */
        get: operations["getPublicProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Submissions I have posted */
        get: operations["listMySubmissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reviews I have written */
        get: operations["listMyReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/reviews-received": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reviews on my submissions */
        get: operations["listReviewsReceived"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/technologies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Technology tag list
         * @description All technology tags, alphabetical, for pickers and filters. Public.
         */
        get: operations["listTechnologies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post a review request
         * @description Creates a submission with its evaluation criteria and technology tags in one transaction. The author is always the signed-in user. The repository URL must be exactly https://github.com/{owner}/{repo}. Criteria are fixed at creation and cannot be edited afterwards. Returns the new submission in the same shape as the detail endpoint. Subject to the write rate limit.
         */
        post: operations["createSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Submission detail
         * @description A submission with its criteria, every review, and its repository snapshot when one exists. Public.
         */
        get: operations["getSubmission"];
        /**
         * Edit own review request
         * @description Replaces the four editable fields of a submission: title, description, repository URL and technologies. All four are required. Only the author may edit it. Criteria cannot be changed and are not accepted at all, because existing ratings point at them. When the repository URL changes, the cached repository snapshot is cleared and fetched again later. Returns the updated submission in the same shape as the detail endpoint. Subject to the write rate limit. Does not use the Idempotency-Key header, since replaying an edit changes nothing, and the header is ignored.
         */
        put: operations["updateSubmission"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review a submission
         * @description Posts a review and awards the reviewer karma in one transaction. The reviewer is always the signed-in user and the karma goes to the reviewer, never to the submission's author. A review rates every criterion of the submission exactly once, so ratings for a subset, or for criteria of another submission, are rejected with 400 CRITERIA_MISMATCH. The author cannot review their own submission (403), and a second review of the same submission by the same person is rejected with 409. Returns the stored review and the reviewer's new karma total, so a client can update its karma display without another request. Subject to the write rate limit.
         */
        post: operations["createReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public feed
         * @description Submissions newest first, with optional search and technology filters. Public.
         */
        get: operations["listFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feed/personalized": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Personalized feed
         * @description The most recent 200 submissions by other users, ranked by overlap with the signed-in user's technology stack blended with recency. A user with no technologies gets recency order.  The user's own submissions are excluded; they appear in the public feed and in /users/me/submissions.
         */
        get: operations["listPersonalizedFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ErrorCode: "VALIDATION_ERROR" | "INVALID_REPO_URL" | "CRITERIA_MISMATCH" | "IDEMPOTENCY_KEY_REUSED" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "REQUEST_IN_PROGRESS" | "PAYLOAD_TOO_LARGE" | "RATE_LIMITED" | "INTERNAL" | "REQUEST_TIMEOUT" | "SERVICE_UNAVAILABLE";
        ErrorEnvelope: {
            /** @constant */
            success: false;
            error: {
                code: components["schemas"]["ErrorCode"];
                message: string;
                /** Format: uuid */
                requestId: string;
            };
        };
        HealthLiveResponse: {
            /** @constant */
            success: true;
            data: {
                /** @constant */
                status: "ok";
            };
        };
        HealthReadyResponse: {
            /** @constant */
            success: true;
            data: {
                /** @constant */
                status: "ready";
            };
        };
        Technology: {
            id: number;
            name: string;
        };
        MeResponse: {
            /** @constant */
            success: true;
            data: {
                id: number;
                username: string;
                bio: string | null;
                karma: number;
                /** Format: date-time */
                createdAt: string;
                technologies: components["schemas"]["Technology"][];
                stats: {
                    submissions: number;
                    reviewsGiven: number;
                    reviewsReceived: number;
                };
            };
        };
        UpdateMeRequest: {
            /** @description Trimmed and lowercased, then must match the pattern. Reserved names are rejected. */
            username?: string;
            /** @description Trimmed. An empty string or null clears it. */
            bio?: string | null;
            /** @description Replaces the whole stack. Names are trimmed, lowercased and de-duplicated. Unknown names are created. */
            technologies?: string[];
        };
        PublicProfileResponse: {
            /** @constant */
            success: true;
            data: {
                username: string;
                bio: string | null;
                karma: number;
                /** Format: date-time */
                createdAt: string;
                technologies: components["schemas"]["Technology"][];
                stats: {
                    submissions: number;
                    reviewsGiven: number;
                    reviewsReceived: number;
                };
            };
        };
        PaginationMeta: {
            totalItems: number;
            currentPage: number;
            totalPages: number;
            itemsPerPage: number;
        };
        SubmissionSummary: {
            id: number;
            title: string;
            /** Format: uri */
            githubUrl: string;
            /** Format: date-time */
            createdAt: string;
            technologies: components["schemas"]["Technology"][];
            reviewCount: number;
        };
        ReviewSummary: {
            id: number;
            feedback: string;
            /** Format: date-time */
            createdAt: string;
            ratings: {
                criterion: string;
                rating: number;
            }[];
            submission: {
                id: number;
                title: string;
                /** @description Username of the submission's author */
                author: string;
            };
            /** @description Username of the review's author */
            reviewer: string;
        };
        SubmissionListResponse: {
            /** @constant */
            success: true;
            data: components["schemas"]["SubmissionSummary"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        ReviewListResponse: {
            /** @constant */
            success: true;
            data: components["schemas"]["ReviewSummary"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        TechnologyListResponse: {
            /** @constant */
            success: true;
            data: components["schemas"]["Technology"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        CreateSubmissionRequest: {
            title: string;
            description: string;
            /** @description Exactly https://github.com/{owner}/{repo}: the https scheme, the host github.com in lowercase, and no trailing slash, port, query, fragment or .git suffix. Surrounding whitespace is trimmed. Any other shape is rejected with 400 INVALID_REPO_URL. */
            githubUrl: string;
            /** @description What reviewers will rate. Fixed once the submission exists. Labels must be unique within the submission, compared case-insensitively. */
            criteria: {
                label: string;
            }[];
            /** @description Names are trimmed, lowercased and de-duplicated, and the limits apply after that. Unknown names are created. */
            technologies: string[];
        };
        UpdateSubmissionRequest: {
            title: string;
            description: string;
            /** @description Exactly https://github.com/{owner}/{repo}, with the same rules as when posting. Changing it clears the cached repository snapshot. Any other shape is rejected with 400 INVALID_REPO_URL. */
            githubUrl: string;
            /** @description Replaces the submission's technologies. Names are trimmed, lowercased and de-duplicated, and the limits apply after that. Unknown names are created. */
            technologies: string[];
        };
        SubmissionDetailResponse: {
            /** @constant */
            success: true;
            data: {
                id: number;
                title: string;
                description: string;
                /** Format: uri */
                githubUrl: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
                /**
                 * @description Derived from the review count on every read (D-14).
                 * @enum {string}
                 */
                status: "PENDING" | "REVIEWED";
                author: {
                    username: string;
                    karma: number;
                };
                technologies: components["schemas"]["Technology"][];
                criteria: {
                    id: number;
                    label: string;
                    /** @description Mean across all reviews, two decimals. null when unreviewed. */
                    averageRating: number | null;
                }[];
                reviewCount: number;
                /** @description Every review, newest first. */
                reviews: {
                    id: number;
                    feedback: string;
                    /** Format: date-time */
                    createdAt: string;
                    /** @description The reviewer's username */
                    reviewer: string;
                    ratings: {
                        criterionId: number;
                        rating: number;
                    }[];
                }[];
                /** @description GitHub metadata. null until fetched, and possibly permanently. */
                repository: null | {
                    stars: number;
                    primaryLanguage: string | null;
                    /** Format: date-time */
                    lastPushedAt: string | null;
                    /** Format: date-time */
                    fetchedAt: string;
                };
            };
        };
        CreateReviewRequest: {
            feedback: string;
            /** @description One entry per criterion of the submission, exactly. A criterion cannot appear twice. Ratings that do not match the submission's criteria are rejected with 400 CRITERIA_MISMATCH. */
            ratings: {
                criterionId: number;
                rating: number;
            }[];
        };
        CreateReviewResponse: {
            /** @constant */
            success: true;
            data: {
                review: {
                    id: number;
                    submissionId: number;
                    feedback: string;
                    /** Format: date-time */
                    createdAt: string;
                    /** @description The reviewer's username */
                    reviewer: string;
                    /** @description Ordered by criterion id. */
                    ratings: {
                        criterionId: number;
                        rating: number;
                    }[];
                };
                /** @description The reviewer's karma total after this review. */
                reviewerKarma: number;
            };
        };
        FeedItem: {
            id: number;
            title: string;
            description: string;
            /** Format: uri */
            githubUrl: string;
            /** Format: date-time */
            createdAt: string;
            /** @enum {string} */
            status: "PENDING" | "REVIEWED";
            author: {
                username: string;
                karma: number;
            };
            technologies: components["schemas"]["Technology"][];
            reviewCount: number;
        };
        FeedResponse: {
            /** @constant */
            success: true;
            data: components["schemas"]["FeedItem"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        PersonalizedFeedItem: {
            id: number;
            title: string;
            description: string;
            /** Format: uri */
            githubUrl: string;
            /** Format: date-time */
            createdAt: string;
            /** @enum {string} */
            status: "PENDING" | "REVIEWED";
            author: {
                username: string;
                karma: number;
            };
            technologies: components["schemas"]["Technology"][];
            reviewCount: number;
            /** @description Tags this submission shares with the signed-in user's stack. */
            matchedTechnologies: string[];
            /** @description Present only with ?debug=1 outside production. Never in production responses. */
            _score?: {
                final: number;
                tag: number;
                recency: number;
            };
        };
        PersonalizedFeedResponse: {
            /** @constant */
            success: true;
            data: components["schemas"]["PersonalizedFeedItem"][];
            meta: components["schemas"]["PaginationMeta"];
        };
    };
    responses: {
        /** @description Unexpected server error. The message is deliberately generic; the requestId maps to the full details in the logs. */
        InternalError: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "INTERNAL",
                 *         "message": "Something went wrong",
                 *         "requestId": "3f1c2a9e-8b7d-4e6f-9a1b-2c3d4e5f6a7b"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The service cannot serve traffic right now. SERVICE_UNAVAILABLE when a dependency such as the database is unreachable, REQUEST_TIMEOUT when the request exceeded REQUEST_TIMEOUT_MS. */
        ServiceUnavailable: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "SERVICE_UNAVAILABLE",
                 *         "message": "Service is not ready",
                 *         "requestId": "3f1c2a9e-8b7d-4e6f-9a1b-2c3d4e5f6a7b"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description No valid session. The Authorization header is missing, invalid, or expired. */
        Unauthorized: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "UNAUTHORIZED",
                 *         "message": "Authentication required",
                 *         "requestId": "3f1c2a9e-8b7d-4e6f-9a1b-2c3d4e5f6a7b"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The request did not match the route's schema, including any unexpected field. */
        BadRequest: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "VALIDATION_ERROR",
                 *         "message": "query: Unrecognized key: \"foo\"",
                 *         "requestId": "3f1c2a9e-8b7d-4e6f-9a1b-2c3d4e5f6a7b"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Rate limit exceeded. The RateLimit headers say when the window resets. */
        TooManyRequests: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The request conflicts with existing data, such as a username that is already taken or a submission the caller has already reviewed. */
        Conflict: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "CONFLICT",
                 *         "message": "That username is already taken",
                 *         "requestId": "3f1c2a9e-8b7d-4e6f-9a1b-2c3d4e5f6a7b"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The caller is signed in but may not do this, such as editing someone else's submission. */
        Forbidden: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "FORBIDDEN",
                 *         "message": "You can only edit your own submissions",
                 *         "requestId": "3f1c2a9e-8b7d-4e6f-9a1b-2c3d4e5f6a7b"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description The requested resource does not exist. */
        NotFound: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "error": {
                 *         "code": "NOT_FOUND",
                 *         "message": "User not found",
                 *         "requestId": "3f1c2a9e-8b7d-4e6f-9a1b-2c3d4e5f6a7b"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        Page: number;
        /** @description Above 50 is rejected with 400, never clamped. */
        Limit: number;
    };
    requestBodies: never;
    headers: {
        /** @description Correlation id generated by the server for this request. Matches the requestId in any error body and the reqId on every log line for the request. Any value sent by the client is ignored. */
        XRequestId: string;
        /** @description public, max-age=0, must-revalidate. Stored, but rechecked on every request. */
        CacheControlRevalidate: string;
        /** @description public, max-age=300. Reusable for five minutes without asking. */
        CacheControlFiveMinutes: string;
        /** @description Send back as If-None-Match to get 304 when unchanged. */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is alive. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthLiveResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is ready to serve traffic. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReadyResponse"];
                };
            };
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in user's profile. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description The updated profile. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getPublicProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user's public profile. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProfileResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    listMySubmissions: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                /** @description Above 50 is rejected with 400, never clamped. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of the signed-in user's submissions, newest first. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listMyReviews: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                /** @description Above 50 is rejected with 400, never clamped. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of the reviews the signed-in user has written, newest first. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listReviewsReceived: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                /** @description Above 50 is rejected with 400, never clamped. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of the reviews other users wrote on the signed-in user's submissions, newest first. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listTechnologies: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                /** @description Above 50 is rejected with 400, never clamped. */
                limit?: components["parameters"]["Limit"];
                /** @description Case-insensitive substring match on the tag name, for type-to-filter pickers. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of technology tags. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "Cache-Control": components["headers"]["CacheControlFiveMinutes"];
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnologyListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    createSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubmissionRequest"];
            };
        };
        responses: {
            /** @description The new submission. */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDetailResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The submission. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDetailResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    updateSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSubmissionRequest"];
            };
        };
        responses: {
            /** @description The updated submission. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDetailResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewRequest"];
            };
        };
        responses: {
            /** @description The stored review and the reviewer's new karma total. */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateReviewResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listFeed: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                /** @description Above 50 is rejected with 400, never clamped. */
                limit?: components["parameters"]["Limit"];
                /** @description Case-insensitive match against title and description. */
                search?: string;
                /** @description Comma-separated technology names. Returns submissions with any of them. Names are trimmed, lowercased and de-duplicated, up to 10. */
                technologies?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of the feed. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    "Cache-Control": components["headers"]["CacheControlRevalidate"];
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedResponse"];
                };
            };
            /** @description Not modified. The If-None-Match value still matches the current feed. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    listPersonalizedFeed: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                /** @description Above 50 is rejected with 400, never clamped. */
                limit?: components["parameters"]["Limit"];
                /** @description Set to 1 for a score breakdown per item. Ignored in production. */
                debug?: "1";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of the ranked feed. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalizedFeedResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
}
